version: '3.8'

services:
  db:
    image: postgres:16
    platform: linux/amd64
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: concifa
      POSTGRES_PASSWORD: concifa123
      POSTGRES_DB: concifa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - concifa-network

networks:
  concifa-network:
    driver: bridge

volumes:
  postgres_data: 